// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Data.Migrations
{
    [DbContext(typeof(AnalogAgendaDbContext))]
    [Migration("20260416104658_AddIndexForCollectionsIDCollectionIndex")]
    partial class AddIndexForCollectionsIDCollectionIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.CollectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsOpen");

                    b.HasIndex("Owner");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Database.Entities.CollectionPhotoEntity", b =>
                {
                    b.Property<string>("CollectionsId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotosId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CollectionIndex")
                        .HasColumnType("int")
                        .HasColumnName("Index");

                    b.Property<string>("FilmId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CollectionsId", "PhotosId");

                    b.HasIndex("PhotosId");

                    b.HasIndex("CollectionsId", "CollectionIndex")
                        .IsUnique();

                    b.ToTable("CollectionPhotos", (string)null);
                });

            modelBuilder.Entity("Database.Entities.DevKitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Expired")
                        .HasColumnType("bit");

                    b.Property<int>("FilmsDeveloped")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("MixedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PurchasedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ValidForFilms")
                        .HasColumnType("int");

                    b.Property<int>("ValidForWeeks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Expired");

                    b.HasIndex("MixedOn");

                    b.ToTable("DevKits");
                });

            modelBuilder.Entity("Database.Entities.DevKitFilmEntity", b =>
                {
                    b.Property<string>("DevKitId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilmId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DevKitId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("DevKitFilms", (string)null);
                });

            modelBuilder.Entity("Database.Entities.DevKitSessionEntity", b =>
                {
                    b.Property<string>("DevKitId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DevKitId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("DevKitSessions", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ExposureDateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilmId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("ExposureDates");
                });

            modelBuilder.Entity("Database.Entities.FilmEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Developed")
                        .HasColumnType("bit");

                    b.Property<string>("DevelopedInSessionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DevelopedWithDevKitId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfExposures")
                        .HasColumnType("int");

                    b.Property<int>("PurchasedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Developed");

                    b.HasIndex("DevelopedInSessionId");

                    b.HasIndex("DevelopedWithDevKitId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("Database.Entities.IdeaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Database.Entities.IdeaPhotoEntity", b =>
                {
                    b.Property<string>("IdeaId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdeaId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.ToTable("IdeaPhotos", (string)null);
                });

            modelBuilder.Entity("Database.Entities.IdeaSessionEntity", b =>
                {
                    b.Property<string>("IdeaId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdeaId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("IdeaSessions", (string)null);
                });

            modelBuilder.Entity("Database.Entities.NoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SideNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("TemperatureMax")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("float");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteEntries");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryOverrideEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FilmCountMax")
                        .HasColumnType("int");

                    b.Property<int>("FilmCountMin")
                        .HasColumnType("int");

                    b.Property<string>("NoteEntryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Step")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("TemperatureMax")
                        .HasColumnType("float");

                    b.Property<double?>("TemperatureMin")
                        .HasColumnType("float");

                    b.Property<double?>("Time")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NoteEntryId");

                    b.ToTable("NoteEntryOverrides");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmInterval")
                        .HasColumnType("int");

                    b.Property<string>("NoteEntryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TimeIncrement")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NoteEntryId");

                    b.ToTable("NoteEntryRules");
                });

            modelBuilder.Entity("Database.Entities.PhotoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilmId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("Restricted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("FilmId", "Index")
                        .IsUnique();

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Database.Entities.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Index"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Index")
                        .IsUnique();

                    b.HasIndex("SessionDate");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Database.Entities.UsedDevKitThumbnailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DevKitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UsedDevKitThumbnails");
                });

            modelBuilder.Entity("Database.Entities.UsedFilmThumbnailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UsedFilmThumbnails");
                });

            modelBuilder.Entity("Database.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.Entities.UserSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentFilmId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntitiesPerPage")
                        .HasColumnType("int");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<bool>("TableView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentFilmId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("SessionDevKit", b =>
                {
                    b.Property<string>("DevKitId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DevKitId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionDevKit");
                });

            modelBuilder.Entity("Database.Entities.CollectionPhotoEntity", b =>
                {
                    b.HasOne("Database.Entities.CollectionEntity", "Collection")
                        .WithMany("CollectionPhotoLinks")
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.PhotoEntity", "Photo")
                        .WithMany("CollectionPhotoLinks")
                        .HasForeignKey("PhotosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Database.Entities.DevKitFilmEntity", b =>
                {
                    b.HasOne("Database.Entities.DevKitEntity", "DevKit")
                        .WithMany()
                        .HasForeignKey("DevKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.FilmEntity", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevKit");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Database.Entities.DevKitSessionEntity", b =>
                {
                    b.HasOne("Database.Entities.DevKitEntity", "DevKit")
                        .WithMany()
                        .HasForeignKey("DevKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.SessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevKit");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Database.Entities.ExposureDateEntity", b =>
                {
                    b.HasOne("Database.Entities.FilmEntity", "Film")
                        .WithMany("ExposureDates")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Database.Entities.FilmEntity", b =>
                {
                    b.HasOne("Database.Entities.SessionEntity", "DevelopedInSession")
                        .WithMany("DevelopedFilms")
                        .HasForeignKey("DevelopedInSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Database.Entities.DevKitEntity", "DevelopedWithDevKit")
                        .WithMany("DevelopedFilms")
                        .HasForeignKey("DevelopedWithDevKitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DevelopedInSession");

                    b.Navigation("DevelopedWithDevKit");
                });

            modelBuilder.Entity("Database.Entities.IdeaPhotoEntity", b =>
                {
                    b.HasOne("Database.Entities.IdeaEntity", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.PhotoEntity", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Database.Entities.IdeaSessionEntity", b =>
                {
                    b.HasOne("Database.Entities.IdeaEntity", "Idea")
                        .WithMany("IdeaSessions")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.SessionEntity", "Session")
                        .WithMany("IdeaSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryEntity", b =>
                {
                    b.HasOne("Database.Entities.NoteEntity", "Note")
                        .WithMany("Entries")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryOverrideEntity", b =>
                {
                    b.HasOne("Database.Entities.NoteEntryEntity", "NoteEntry")
                        .WithMany("Overrides")
                        .HasForeignKey("NoteEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteEntry");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryRuleEntity", b =>
                {
                    b.HasOne("Database.Entities.NoteEntryEntity", "NoteEntry")
                        .WithMany("Rules")
                        .HasForeignKey("NoteEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteEntry");
                });

            modelBuilder.Entity("Database.Entities.PhotoEntity", b =>
                {
                    b.HasOne("Database.Entities.FilmEntity", "Film")
                        .WithMany("Photos")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Database.Entities.UserSettingsEntity", b =>
                {
                    b.HasOne("Database.Entities.FilmEntity", "CurrentFilm")
                        .WithMany()
                        .HasForeignKey("CurrentFilmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Database.Entities.UserEntity", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("Database.Entities.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentFilm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionDevKit", b =>
                {
                    b.HasOne("Database.Entities.DevKitEntity", null)
                        .WithMany()
                        .HasForeignKey("DevKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.CollectionEntity", b =>
                {
                    b.Navigation("CollectionPhotoLinks");
                });

            modelBuilder.Entity("Database.Entities.DevKitEntity", b =>
                {
                    b.Navigation("DevelopedFilms");
                });

            modelBuilder.Entity("Database.Entities.FilmEntity", b =>
                {
                    b.Navigation("ExposureDates");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Database.Entities.IdeaEntity", b =>
                {
                    b.Navigation("IdeaSessions");
                });

            modelBuilder.Entity("Database.Entities.NoteEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Database.Entities.NoteEntryEntity", b =>
                {
                    b.Navigation("Overrides");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Database.Entities.PhotoEntity", b =>
                {
                    b.Navigation("CollectionPhotoLinks");
                });

            modelBuilder.Entity("Database.Entities.SessionEntity", b =>
                {
                    b.Navigation("DevelopedFilms");

                    b.Navigation("IdeaSessions");
                });

            modelBuilder.Entity("Database.Entities.UserEntity", b =>
                {
                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
